[project]
name = "clod"
version = "0.1.0"
description = "Tool for managing local Claude Code projects/conversations."
authors = [{name = "Matthew W. Hoffman"}]
requires-python = ">=3.10"
dependencies = [
  "humanize>=4.16.0",
  "rich>=15.0.0",
  "typer>=0.27.2",
]

[project.scripts]
clod = "clod.cli:app"

[dependency-groups]
dev = [
  "ruff",
  "ty",
]

[build-system]
requires = ["uv_build>=0.12,<0.13"]
build-backend = "uv_build"

[tool.uv]
# Should match the version requirements of uv_build above.
required-version = ">=0.12,<0.13"
